---
ntp_manage: true
ntp_manage_timezone: true
ntp_manage_chrony: true
ntp_timezone: UTC
ntp_chrony_remove_ntpd: true
ntp_chrony_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org