---
- name: set up time zone symlink
  file:
    src: "{{ timezone_file }}"
    dest: /etc/localtime
    owner: root
    group: root
    state: link

- name: configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: ensure ntp is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp