---
- name: Configure php to use mailhog
  lineinfile:
    dest: "/etc/php.ini"
    regexp: "^sendmail_path = /usr/sbin/sendmail -t -i"
    line: "sendmail_path = /opt/mailhog/mhsendmail"
    state: present
  notify:
    - restart apache
    - restart php-fpm
  when: mailhog_configure_php